//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShepherdAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyType
    {
        public CurrencyType()
        {
            this.MemberObligations = new HashSet<MemberObligation>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int ID { get; set; }
        public string CurrencyName { get; set; }
        public string ShortName { get; set; }
        public string RecordedBy { get; set; }
        public System.DateTime DateRecorded { get; set; }
    
        public virtual ICollection<MemberObligation> MemberObligations { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
