//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShepherdAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public Institution()
        {
            this.AspNetGroups = new HashSet<AspNetGroup>();
            this.Members = new HashSet<Member>();
            this.MemberSacraments = new HashSet<MemberSacrament>();
            this.MemberTypes = new HashSet<MemberType>();
            this.ObligationTypes = new HashSet<ObligationType>();
            this.OrganizationPositionTypes = new HashSet<OrganizationPositionType>();
            this.Organizations = new HashSet<Organization>();
            this.PositionTypes = new HashSet<PositionType>();
            this.SalutationTypes = new HashSet<SalutationType>();
        }
    
        public int ID { get; set; }
        public int InstitutionGroupID { get; set; }
        public string InstitutionName { get; set; }
        public string Initial { get; set; }
        public string OfficePhone { get; set; }
        public string MobilePhone { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public int StatusTypeID { get; set; }
        public string RecordedBy { get; set; }
        public System.DateTime DateRecorded { get; set; }
    
        public virtual ICollection<AspNetGroup> AspNetGroups { get; set; }
        public virtual InstitutionGroup InstitutionGroup { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<MemberSacrament> MemberSacraments { get; set; }
        public virtual ICollection<MemberType> MemberTypes { get; set; }
        public virtual ICollection<ObligationType> ObligationTypes { get; set; }
        public virtual ICollection<OrganizationPositionType> OrganizationPositionTypes { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<PositionType> PositionTypes { get; set; }
        public virtual ICollection<SalutationType> SalutationTypes { get; set; }
    }
}
