//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShepherdAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.MemberDocuments = new HashSet<MemberDocument>();
            this.MemberObligations = new HashSet<MemberObligation>();
            this.MemberPayments = new HashSet<MemberPayment>();
            this.MemberPhotos = new HashSet<MemberPhoto>();
            this.MemberSacraments = new HashSet<MemberSacrament>();
            this.OrganizationLeaders = new HashSet<OrganizationLeader>();
            this.OrganizationMembers = new HashSet<OrganizationMember>();
        }
    
        public int ID { get; set; }
        public int InstitutionID { get; set; }
        public string MemberID { get; set; }
        public int SalutationTypeID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int GenderTypeID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int MaritalStatusTypeID { get; set; }
        public string ResidentAddress { get; set; }
        public string EmailAddress { get; set; }
        public string MobilePhone { get; set; }
        public string OfficePhone { get; set; }
        public int NationalityTypeID { get; set; }
        public Nullable<int> CountyID { get; set; }
        public string Region { get; set; }
        public int MemberTypeID { get; set; }
        public int StatusTypeID { get; set; }
        public string PhotoPath { get; set; }
        public string UserID { get; set; }
        public string RecordedBy { get; set; }
        public System.DateTime DateRecorded { get; set; }
    
        public virtual County County { get; set; }
        public virtual GenderType GenderType { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual MaritalStatusType MaritalStatusType { get; set; }
        public virtual ICollection<MemberDocument> MemberDocuments { get; set; }
        public virtual ICollection<MemberObligation> MemberObligations { get; set; }
        public virtual ICollection<MemberPayment> MemberPayments { get; set; }
        public virtual ICollection<MemberPhoto> MemberPhotos { get; set; }
        public virtual MemberType MemberType { get; set; }
        public virtual NationalityType NationalityType { get; set; }
        public virtual SalutationType SalutationType { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual ICollection<MemberSacrament> MemberSacraments { get; set; }
        public virtual ICollection<OrganizationLeader> OrganizationLeaders { get; set; }
        public virtual ICollection<OrganizationMember> OrganizationMembers { get; set; }
    }
}
