//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShepherdAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPayment
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public int PaymentID { get; set; }
        public int MemberObligationID { get; set; }
        public string Remark { get; set; }
        public string RecordedBy { get; set; }
        public System.DateTime DateRecorded { get; set; }
    
        public virtual MemberObligation MemberObligation { get; set; }
        public virtual Member Member { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
