//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShepherdAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationLeader
    {
        public int ID { get; set; }
        public int OrganizationID { get; set; }
        public int MemberID { get; set; }
        public int OrganizationPositionTypeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int StatusID { get; set; }
        public string RecordedBy { get; set; }
        public System.DateTime DateRecorded { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual OrganizationPositionType OrganizationPositionType { get; set; }
        public virtual StatusType StatusType { get; set; }
    }
}
