//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShepherdAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sacrament
    {
        public Sacrament()
        {
            this.MemberSacraments = new HashSet<MemberSacrament>();
            this.SacramentRequirements = new HashSet<SacramentRequirement>();
            this.SacramentRequirements1 = new HashSet<SacramentRequirement>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool AppliedOnce { get; set; }
        public bool NotOnSameDay { get; set; }
        public string Description { get; set; }
        public string RecordedBy { get; set; }
        public System.DateTime DateRecorded { get; set; }
    
        public virtual ICollection<MemberSacrament> MemberSacraments { get; set; }
        public virtual ICollection<SacramentRequirement> SacramentRequirements { get; set; }
        public virtual ICollection<SacramentRequirement> SacramentRequirements1 { get; set; }
    }
}
