//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShepherdAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusType
    {
        public StatusType()
        {
            this.Institutions = new HashSet<Institution>();
            this.Members = new HashSet<Member>();
            this.OrganizationLeaders = new HashSet<OrganizationLeader>();
            this.OrganizationMembers = new HashSet<OrganizationMember>();
        }
    
        public int ID { get; set; }
        public string StatusName { get; set; }
        public string RecordedBy { get; set; }
        public System.DateTime DateRecorded { get; set; }
    
        public virtual ICollection<Institution> Institutions { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<OrganizationLeader> OrganizationLeaders { get; set; }
        public virtual ICollection<OrganizationMember> OrganizationMembers { get; set; }
    }
}
