//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShepherdAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracker
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string IpAddress { get; set; }
        public string AreaAccessed { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string PreviousValues { get; set; }
    }
}
